---
title: Pirâmides etárias do Brasil, regiões e estados utilizando a projeção populacional
  do IBGE (2010-2060)
author: "Leonardo Goes Shibata"
date: "23/10/2019"
output: github_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# install and load required packages
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse)
pacman::p_load(readxl)
pacman::p_load_gh("krlmlr/here")
```


```{r data_download, include=FALSE}
# Download projeção da população
if (file.exists(here("data", "projecoes_2018_populacao_2010_2060.xls")) == FALSE) {
  url <- "ftp://ftp.ibge.gov.br/Projecao_da_Populacao/Projecao_da_Populacao_2018/projecoes_2018_populacao_2010_2060.xls"
  download.file(url, destfile = here("data", "projecoes_2018_populacao_2010_2060.xls"),
                mode = "wb")
}
```


```{r functions, include=FALSE}
absolute_format <- function(accuracy = 1, scale = 1, prefix = "",
                          suffix = "", big.mark = ".", decimal.mark = ",",
                          trim = TRUE, ...) {
  function(x) scales::number(
      abs(x),
      accuracy = accuracy,
      scale = scale,
      prefix = prefix,
      suffix = suffix,
      big.mark = big.mark,
      decimal.mark = decimal.mark,
      trim = trim,
      ...
    )
}

plot_pyramid <- function(estado) {
  homens <- read_xls(path = here("data", "projecoes_2018_populacao_2010_2060.xls"),
                     sheet = estado,
                     range = "A5:AZ25")
  
  mulheres <- read_xls(path = here("data", "projecoes_2018_populacao_2010_2060.xls"),
                       sheet = estado,
                       range = "A28:AZ48")
  
  homens2 <- homens %>%
    pivot_longer(cols = -1, # all but the first
                 names_to = "ano",
                 values_to = "populacao") %>%
    filter(`GRUPO ETÁRIO`!="Total",
           ano %in% c("2010", "2020", "2030", "2040", "2050", "2060")) %>%
    mutate(faixa_etaria = factor(`GRUPO ETÁRIO`,
                                 levels = unique(`GRUPO ETÁRIO`),
                                 ordered = TRUE))
  
  mulheres2 <- mulheres %>%
    pivot_longer(cols = -1, # all but the first
                 names_to = "ano",
                 values_to = "populacao") %>%
    filter(`GRUPO ETÁRIO`!="Total",
           ano %in% c("2010", "2020", "2030", "2040", "2050", "2060")) %>%
    mutate(faixa_etaria = factor(`GRUPO ETÁRIO`,
                                 levels = unique(`GRUPO ETÁRIO`),
                                 ordered = TRUE))
  
  print(
    ggplot(data = homens2, aes(x = faixa_etaria, y = populacao)) +
    geom_col(data = homens2, aes(y = -populacao, fill = "Homens")) +
    geom_col(data = mulheres2, aes(fill = "Mulheres")) +
    coord_flip() +
    scale_y_continuous(labels = absolute_format(scale = 10^-3, suffix = " mil")) +
    facet_wrap("ano") +
    scale_fill_manual(name = "", values = c(Homens = "#3E606F", Mulheres = "#8C3F4D"),
                 labels = c("Homens", "Mulheres")) +
    ggtitle(estado)
  )
}
```


```{r plot, fig.height=10, fig.width=15}
sheets <- excel_sheets(here("data", "projecoes_2018_populacao_2010_2060.xls"))[-1]

walk(sheets, plot_pyramid)
```


